DemoCodeFirst/DemoCodeFirst/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoCodeFirst.Models;

namespace DemoCodeFirst.Controllers
{
    public class StudentsController : Controller
    {
        private ManagerStudentContext db;
        public StudentsController()
        {
            if (db == null)
            {
                db = new ManagerStudentContext();
            }
        }
        // GET: Students
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListStudent(String KeySearch, int CurrentPage)
        {
            try
            {
                var list = db.Students.ToList();
             //   var list = db.Students.Where(p => p.FullName.Contains(KeySearch)).ToList());
                var TotalPage = list.Count() % 4 == 0 ? list.Count() / 4 : (list.Count() / 4) + 1;
                var result = list.Skip((CurrentPage - 1) * 4).Take(4).ToList();
                return Json(new {code = 200, TotalPage = TotalPage, list = result, msg = "Success" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new {code = 500, msg = "Get List Student Failed" }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult Add(string StudentId, string FullName, DateTime BirthDay)
        {
            try
            {
                Student student = new Student()
                {
                    StudentId = StudentId,
                    FullName = FullName,
                    BirthDay = BirthDay
                };
                db.Students.Add(student);
                db.SaveChanges();
                var TotalPage = db.Students.Count() % 4 == 0 ? db.Students.Count() / 4 : (db.Students.Count() / 4) + 1;
                return Json(new { code = 200, TotalPage = TotalPage, msg = "Add Success" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Add Faild" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                var student = db.Students.Find(id);
                db.Students.Remove(student);
                db.SaveChanges();
                var TotalPage = db.Students.Count() % 4 == 0 ? db.Students.Count() / 4 : (db.Students.Count() / 4) + 1;
                return Json(new { code = 200, TotalPage = TotalPage, msg = "Record delete success" }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(new { code = 500, msg = "Record is invalid or deleted :" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult DeleteAll(string[] selectedID)
        {
            try
            {
                foreach (string id in selectedID)
                {
                    Student obj = db.Students.Find(id);
                    db.Students.Remove(obj);
                }
                db.SaveChanges();

                var TotalPage = db.Students.Count() % 4 == 0 ? db.Students.Count() / 4 : (db.Students.Count() / 4) + 1;
                return Json(new { code = 200, TotalPage = TotalPage, msg = "All the customers deleted successfully!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Deleted failed! - " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Edit(string id, string FullName, DateTime BirthDay)
        {
            try
            {
                var query = db.Students.Single(s => s.StudentId.Equals(id));


                query.FullName = FullName;
                query.BirthDay = BirthDay;
                db.SaveChanges();
                return Json(" Edited successfully!");
            }
            catch (Exception ex)
            {
                return Json("Editted failed! - " + ex.Message);
            }
        }
    }
}

DemoCodeFirst/DemoCodeFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/moment-with-locales.min.js"></script>

    @RenderSection("MyScript", required: false)
</body>
</html>

DemoCodeFirst/DemoCodeFirst/Views/Shared/_partial_add_student.cshtml
@model DemoCodeFirst.Models.Student
<div class="modal" tabindex="-1" role="dialog" id="modal-add-student">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="panel panel-primary">
                <div class="panel-heading">ADD STUDENT</div>
                <div class="panel-body">
                    @using (Ajax.BeginForm("Add", "Students", new AjaxOptions()
                    {
                       // InsertionMode = InsertionMode.InsertAfter,
                        HttpMethod = "POST",
                        OnSuccess = "OnSuccess",
                        OnFailure = "OnFailure",
                       // LoadingElementId = "loadingImage",
                       // UpdateTargetId = "my-data"
                    }))
                    {
                    <div class="form-group">
                        @Html.LabelFor(m => m.StudentId)
                        @Html.EditorFor(m => m.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.FullName)
                        @Html.EditorFor(m => m.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.BirthDay)
                        @Html.EditorFor(m => m.BirthDay, new { htmlAttributes = new { @class = "form-control" } })
                    </div>

                        <button type="submit" class="btn btn-primary" id="btnSave">Save</button>

                    }
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>